### PR TITLE
Updated "here" to "current%20location"

### PR DESCRIPTION
**Pull request by cleggypdc**
Prevents inaccurate directions search results

### CODE REVIEW

**Comment by leecrossley** [comment]
I've merged for now, this was changed in #6 - perhaps there is another way?

**Comment by cleggypdc** [comment]
According to Apple 

"A complete directions request includes the saddr, daddr, and dirflg parameters, but only the daddr parameter is required. If you don’t specify a value for saddr, the starting point is “here.”

https://developer.apple.com/library/ios/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html

Removing the parameter altogether should work :-)

**Comment by cleggypdc** [comment]
But then it may also be useful if devs could specify the start location. So maybe if this was an optional second parameter?

**Comment by leecrossley** [comment]
Makes sense, open the issue for a rainy day, unless you want to PR. Thanks.

**Pull request merged**
